domain_min = [-5.0, -5.0, -1.0]
domain_max = [5.0, 5.0, 1.0]
init_particles = "../Resources/carom.p4p"
wall_normal = [0.0, 0.0, -1.0]
wall_distance = 0.03125
max_coordinate_number = 16
dt = 2.56e-6
target_time = 1.28
saving_interval_time = 2.56e-3
gravity = [0.0, 0.0, -9.81]
