domain_min = [-0.5, -0.5, -0.5]
domain_max = [0.11, 0.5, 0.5]
init_particles = "../Resources/cube_911_particles_impact.p4p"
wall_normal = [1.0, 0.0, 0.0]
wall_distance = 0.02
max_coordinate_number = 16
dt = 1e-7
target_time = 0.01
saving_interval_time = 1e-4
gravity = [0.0, 0.0, 0.0]
