domain_min = [-200.0, -200.0, -30.0]
domain_max = [200.0, 200.0, 90.0]
init_particles = "../Resources/bunny.p4p"
wall_normal = [0.0, 0.0, -1.0]
wall_distance = 25.0
max_coordinate_number = 64
dt = 2.63e-5
target_time = 10.0
saving_interval_time = 0.05
gravity = [0.0, 0.0, -9.81]
